name: Publish Java Layers

on:
  push:
    tags: [master]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter a tagged release to publish.'
        required: true
        type: string

env:
  release_tag: ''

jobs:
  publish-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ java8al2, java11, java17, java21 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set tag env var
        id: release_tag
        run: |
          if [[ ! -z ${{ github.event.inputs.tag }} ]]; then 
            echo "release_tag=${{ github.event.inputs.tag }}_java" >> "$GITHUB_ENV"
            echo "Publishing from workflow_dispatch ${{ github.event.inputs.tag }}_java"
          else
            echo "Publishing from GitHub event"
            echo "release_tag=${{ github.event.ref }}" >> "$GITHUB_ENV"
            echo "Publishing from GitHub event: new tag ${{ github.event.ref }}"
          fi
      - name: Check Tag
        id: java-check-tag
        run: |
          if [[ ${{ env.release_tag }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_java/$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Publish ${{ matrix.java-version }} layer
        if: steps.java-check-tag.outputs.match == 'true'
        run: make publish-${{ matrix.java-version }}-ci
