name: Publish Extension Layer

on:
  push:
    tags:
      - v**_extension
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter a tag to publish an Extension layer.'
        required: true
        type: string

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      - uses: actions/checkout@v4
      - name: Check Tag
        id: extension-check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_extension/$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+(\.[0-9]+)*_extension$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          else
              echo "Not publishing Extension layer; skipping"
          fi
      - name: Install publish dependencies
        if: steps.extension-check-tag.outputs.match == 'true'
        run: pip install -U awscli
      - name: Publish extension layer
        if: steps.python-check-tag.outputs.match == 'true'
        run: |
          cd extension
          ./publish-layer.sh
