name: Publish Node Layers

on:
  push:
    tags: [master]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter a tag to publish a Node layer.'
        required: true
        type: string

jobs:
  publish-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}.x
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Tag
        id: node-check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_nodejs/$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+(\.[0-9]+)*_nodejs$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          else
              echo "Not publishing Node layer; exiting"
              exit 0
          fi
      - name: Run Node ${{ matrix.node-version }} unit tests
        if: steps.node-check-tag.outputs.match == 'true'
        run: cd nodejs && npm ci && npm run test
      - name: Publish layer
        run: make publish-nodejs${{ matrix.node-version }}x-ci
      - name: Upload Unit Test Coverage
        uses: codecov/codecov-action@v3
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: ./nodejs/coverage/unit/lcov.info
         fail_ci_if_error: true
         flags: unit-tests
