name: Lambda Layers Publishing CI

on:
  push:
    tags: [master]
  workflow_dispatch:
    inputs:
      layer_runtime:
        description: 'Which kind of layer should be published?'
        required: true
        type: choice
        options:
          - nodejs
          - python
          - java
          - extension
      tag:
        description: 'Enter a tagged release to publish.'
        required: true
        type: string

jobs:
  publish-layers:
    runs-on: ubuntu-latest
    steps:
      - name: Set env var
        id: release_tag
        run: |
          if [[ ! -z ${{ github.event.inputs.tag }} && ! -z ${{ github.event.inputs.layer_runtime }} ]]; then 
            echo "release_tag=${{ github.event.inputs.tag }}_${{ github.event.inputs.layer_runtime }}" >> "$GITHUB_ENV"
            echo "Publishing from workflow_dispatch $release_tag"
          else
            echo "Publishing from GitHub event"
            echo "release_tag=${{ github.event.ref }}" >> "$GITHUB_ENV"
          fi
        shell: bash
    if: ${{ always() }}
    needs: [publish-node, publish-python, publish-java, publish-extension]
