name: Publish Java Layers

on:
  push:
    tags: [master]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter a tag to publish a Java layer.'
        required: true
        type: string

jobs:
  publish-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ java8al2, java11, java17, java21 ]

    steps:
      - uses: actions/checkout@v4
      - name: Check Tag
        id: java-check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_java/$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.tag }} =~ ^v[0-9]+(\.[0-9]+)*_java$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          else
              echo "Not publishing Java layer; skipping"
          fi
      - name: Publish ${{ matrix.java-version }} layer
        if: steps.java-check-tag.outputs.match == 'true'
        run: make publish-${{ matrix.java-version }}-ci
