name: Lambda Layers Publishing CI

# Automated layer releases are triggered by the creation of new tags, which include (by convention)
# the agent version (semver), an underscore, and the runtime. The actual semantic version doesn't
# cause a release of that agent version, though: the build process always gets the latest agent version.
# Since we always publish the latest version, we don't need a tag input, other than as an indicator of
# which layer type to publish, so the workflow dispatch is just a select menu.

on:
  push:
    tags: [master]
  workflow_dispatch:
    inputs:
      layer_runtime:
        description: 'Which kind of layer should be published?'
        required: true
        type: choice
        options:
          - nodejs
          - python
          - java
          - extension

env:
  release_tag: ''
  release_type: ''


jobs:
  publish-layers:
    runs-on: ubuntu-latest
    steps:
      - name: Set env var
        id: release_tag
        run: |
          if [[ ! -z ${{ github.event.inputs.layer_runtime }} ]]; then 
            echo "release_type=${{ github.event.inputs.layer_runtime }}" >> "$GITHUB_ENV"
            echo "Publishing from workflow_dispatch $release_tag"
          else
            echo "Publishing from GitHub tag creation"
            echo "release_tag=${{ github.event.ref }}" >> "$GITHUB_ENV"
          fi
        shell: bash
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_nodejs/$ || ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_nodejs$ ]]; then
              echo "layer_type=nodejs" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_python/$ || ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_python$ ]]; then
              echo "layer_type=python" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_java/$ || ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_java$ ]]; then
              echo "layer_type=java" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_extension/$ || ${{ env.release_tag }} =~ ^v[0-9]+(\.[0-9]+)*_extension$ ]]; then
              echo "layer_type=extension" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Start Node Publish Workflow
        if: steps.check-tag.outputs.layer_type == 'nodejs'
        uses: ./github/actions/publish-node
      - name: Start Python Publish Workflow
        if: steps.check-tag.outputs.layer_type == 'python'
        uses: ./github/actions/publish-python
      - name: Start Java Publish Workflow
        if: steps.check-tag.outputs.layer_type == 'java'
        uses: ./github/actions/publish-java
      - name: Start Extension Publish Workflow
        if: steps.check-tag.outputs.layer_type == 'extension'
        uses: ./github/actions/publish-extension
